# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["production/__main__.py"]

doc_url = "https://b-Insim.github.io/PStack_overflow_query/"

git_url = "https://github.com/b-Insim/PStack_overflow_query/tree/main/"

def custom_doc_links(name): return None
